name: basdekis.io
author: Costas Basdekis
markdown: redcarpet
highlighter: pygments
baseurl: http://blog.basdekis.io 
description: Architect it till you make it
github: http://www.github.com/costas-basdekis
twitter: https://twitter.com/basdekisc
#facebook: http://www.facebook.com
linkedin: http://uk.linkedin.com/pub/costas-basdekis/47/a7b/847
email: costas.basdekis@gmail.com
#location: 42°2'16"N   70°12'47"W
disqus: basdekisio

##Make sure to edit the above fields, especially for disqus.

